### ISSUE TITLE
Problem with hex values

### ISSUE THREAD

**Issue by GertGr** [Dennis1000/VACS#3]
Hex values starting with a A-F (when using the post-H notation)  give an error. As the accompanying documentation says, a workaround is easy by using the $-sign in front, or inserting a 0 infront of FFh making 0FF. This is just for perfection.,

**Comment by Dennis1000** [comment]
This behavior is by design. You must precede these values with a 0 to distinguish them from identifiers that cannot have a digit as the first number, see VACS-MAN.DOC

*** Identifiers ***

 All symbolic names can have up to 32 significant characters.  Longer names
 may be used, but the excess characters will be ignored.  The names may
 contain letters (a..z, A..Z), digits (0..9), underscores (_), dollar signs
 ($) and commercial 'at' signs (@).  **The first character cannot be a digit.**
 Uppercase and lowercase letters are treated as being the same.  An
 identifier cannot have the name of a reserved word, that is, it cannot have
 the name of a written operator (like MOD), an opcode, register or assembler
 defined constant.  The dollar sign alone cannot be used as an identifier
 name (gives the location counter value as it was at the start of the line).
 Strings starting with a dollar sign and followed by hex digit characters
 cannot be used as identifier names either (they are interpreted as
 hexadecimal constants).
